### ISSUE TITLE
Switch to static site

### ISSUE THREAD

**Issue by bamnet** [concerto/concerto-signage.org#20]
I propose that we switch concerto-signage.org to a static site, with some sort of template + generator.  The content we write isn't really dynamic and we're using Rails for a glorified templating engine.  Converting the site into something static may both simplify development (e.g. just edit the HTML in a pull request) and hosting environment.

**Comment by augustf** [comment]
I believe @brzaik has been having just such a thought. In essence, the site needs some promo pages, help pages, a place for release notes, and links to the demo and newsgroup.

**Comment by bamnet** [comment]
I'm going to take a stab at making this a Jekyll site, I think that's what the cool kids are using these days, right?  Open to any / all suggestions!

**Comment by bamnet** [comment]
Discovery of the night - Despite the fact that this repo _looks_ like the Concerto, site, the real site actually lives over at https://github.com/brzaik/concerto-signage-v2.

**Comment by bamnet** [comment]
Current progress:

- [ ] Deploy
- [X] Overview
- [ ] Why Concerto?
- [ ] Supporters
- [ ] Trademark Policy
- [X] Logos and Graphics

There are a ton of images on the Concerto site.  While I've included all the CSS and JS, I'm only committing images as I see the pages use them.  TBD how we can tree shake some of this CSS / JS.

**Comment by bamnet** [comment]
I've copied over all of the "pages" from the mainsite.  The remaining two sections are the blog and the V1 help pages.

Since the blog is powered by wordpress, I _think_ there might be an importer we can use.

The v1 help content should be pretty simple to port over statically, no clue about the search feature that it uses.

**Comment by augustf** [comment]
I believe we unlinked the v1 doc pages, because people kept demanding random weird v1 features in v2. Maybe best to zip them up for archival download.

**Comment by bamnet** [comment]
Blog is ported over (mostly).  I added disqus for comments (TBD if I imported them correctly) and pulled in our published blog posts.  I discarded anything in draft.

I found one link into the V1 docs - from the footer of our site.  I'll comment it out for now.

**Comment by bamnet** [comment]
I've staged all this at http://www2.concerto-signage.org/.  Would appreciate a second set of eyes / browsers to see how it's looking.  It should be very very close to the real site.

**Comment by bamnet** [comment]
I felt bad leaving the V1 help pages hanging, so I did a very rough job porting them over.  Most of the images seem lost on myrpi.org, but at least the text will stick around.

I think this migration is now done.  I'm going to switch over the site to start point at github pages and see how it goes.  You can tell when you're looking at the static site because it doesn't have an Admin Login button on the bottom right.

**Comment by bamnet** [comment]
Done.  www.concerto-signage.org is not served via Github pages.  As a bonus, we get https working too.

I have a small cleanup left to do to make the apex domain work with https, but that requires me to move DNS from AWS.
