### ISSUE TITLE
import blog posts to medium

### ISSUE THREAD

**Issue by tyrantkhan** [concerto/concerto-signage.org#22]
@augustf  i believe you still need to create a medium account, otherwise i have added everyone to the publication.

The way you import a blog post is: 

1) https://medium.com/p/import

2) 
![screen shot 2017-06-27 at 12 39 45 pm](https://user-images.githubusercontent.com/107844/27599151-d3adc0bc-5b35-11e7-960f-c090ef404128.png)

3) Select add to publication and select concerto.

@bamnet @brzaik  & @augustf are the ones who have blog posts to import.

**Comment by bamnet** [comment]
I think something is missing around step 2.  When i visit /p/import I see a blank page, there's no list of posts with the triple docs as you've highlighted.

![screenshot 2017-07-08 at 6 10 13 pm](https://user-images.githubusercontent.com/81324/27989553-d1cb4144-6408-11e7-8d82-b70081db5321.png)

Do I need to type in the blog url as well?

**Comment by augustf** [comment]
@tyrantkhan I'm unable to find this publication, but you can feel free to import all our posts wherever you like. I don't think the "authors" or particular posts need take much of any action.

**Comment by tyrantkhan** [comment]
It seems I wasn't entirely clear with step 1.

So you go to that url. Link your specific blog post and then it imports it. You would have to do it each time, per blog post. If you guys give me a login url for your medium accts , i can just take care of it quickly. just message me on gchats or on my phone.

**Comment by bamnet** [comment]
I imported the 8 posts from http://www.concerto-signage.org/blog/author/bamnet/.

**Comment by tyrantkhan** [comment]
thanks all for taking care of tfhis!
